//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_information_data
    {
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string job_order_no { get; set; }
        public string plant { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public string finished_goods_code { get; set; }
        public string curing_date { get; set; }
        public Nullable<int> curing_qty { get; set; }
        public Nullable<int> good_item_qty { get; set; }
        public string lot_no { get; set; }
        public string curing_start_date { get; set; }
        public string curing_start_time { get; set; }
        public string curing_end_date { get; set; }
        public string curing_end_time { get; set; }
        public Nullable<int> wip_curing_qty { get; set; }
        public string wip_curing_date { get; set; }
        public string wip_curing_time { get; set; }
        public string wip_curing_user { get; set; }
        public string post_start_date { get; set; }
        public string post_start_time { get; set; }
        public string post_start_user { get; set; }
        public string greasing_date { get; set; }
        public string greasing_time { get; set; }
        public string greasing_user { get; set; }
        public string packing_date { get; set; }
        public string packing_time { get; set; }
        public string packing_user { get; set; }
        public Nullable<int> wip_packing_qty { get; set; }
        public string wip_packing_date { get; set; }
        public string wip_packing_time { get; set; }
        public string wip_packing_user { get; set; }
        public Nullable<int> incoming_qty { get; set; }
        public string incoming_date { get; set; }
        public string incoming_time { get; set; }
        public string incoming_user { get; set; }
        public string rb1_job_no { get; set; }
        public string rb1_compound { get; set; }
        public Nullable<double> rb1_weight { get; set; }
        public string rb1_stock_in_date { get; set; }
        public string rb1_stock_in_time { get; set; }
        public string rb1_stock_in_user { get; set; }
        public string rb1_batch_no1 { get; set; }
        public string rb1_batch_no2 { get; set; }
        public string rb1_batch_no3 { get; set; }
        public string rb1_batch_no4 { get; set; }
        public string rb1_batch_no5 { get; set; }
        public string rb1_batch_no6 { get; set; }
        public string rb1_batch_no7 { get; set; }
        public string rb1_batch_no8 { get; set; }
        public string rb2_job_no { get; set; }
        public string rb2_compound { get; set; }
        public Nullable<double> rb2_weight { get; set; }
        public string rb2_stock_in_date { get; set; }
        public string rb2_stock_in_time { get; set; }
        public string rb2_stock_in_user { get; set; }
        public string rb2_batch_no1 { get; set; }
        public string rb2_batch_no2 { get; set; }
        public string rb2_batch_no3 { get; set; }
        public string rb2_batch_no4 { get; set; }
        public string rb2_batch_no5 { get; set; }
        public string rb2_batch_no6 { get; set; }
        public string rb2_batch_no7 { get; set; }
        public string rb2_batch_no8 { get; set; }
        public string mc1_job_no { get; set; }
        public string mc1_item { get; set; }
        public Nullable<int> mc1_qty { get; set; }
        public string mc1_process { get; set; }
        public string mc1_date { get; set; }
        public string mc1_time { get; set; }
        public string mc1_user { get; set; }
        public string mc1_stock_in_date { get; set; }
        public string mc1_stock_in_time { get; set; }
        public string mc1_stock_in_user { get; set; }
        public string mc2_job_no { get; set; }
        public string mc2_item { get; set; }
        public Nullable<int> mc2_qty { get; set; }
        public string mc2_process { get; set; }
        public string mc2_date { get; set; }
        public string mc2_time { get; set; }
        public string mc2_user { get; set; }
        public string mc2_stock_in_date { get; set; }
        public string mc2_stock_in_time { get; set; }
        public string mc2_stock_in_user { get; set; }
        public string sp1_job_no { get; set; }
        public string sp1_item { get; set; }
        public Nullable<int> sp1_qty { get; set; }
        public string sp1_process { get; set; }
        public string sp1_date { get; set; }
        public string sp1_time { get; set; }
        public string sp1_user { get; set; }
        public string sp1_stock_in_date { get; set; }
        public string sp1_stock_in_time { get; set; }
        public string sp1_stock_in_user { get; set; }
        public string sp2_job_no { get; set; }
        public string sp2_item { get; set; }
        public Nullable<int> sp2_qty { get; set; }
        public string sp2_process { get; set; }
        public string sp2_date { get; set; }
        public string sp2_time { get; set; }
        public string sp2_user { get; set; }
        public string sp2_stock_in_date { get; set; }
        public string sp2_stock_in_time { get; set; }
        public string sp2_stock_in_user { get; set; }
        public string job_status { get; set; }
        public Nullable<int> total_wip { get; set; }
        public string last_process { get; set; }
        public string rb1_process { get; set; }
        public string rb2_process { get; set; }
    }
}
