//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_target
    {
        public string plant { get; set; }
        public string group_cd { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public Nullable<int> qty_wip { get; set; }
        public string status_wip { get; set; }
        public string status_name { get; set; }
        public Nullable<int> stock_day { get; set; }
        public Nullable<int> lot_per_day { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string entry_user { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string update_user { get; set; }
        public string tran_no { get; set; }
    }
}
